import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/Header";
import "./globals.css"

import {Mulish, Inter, Roboto, Open_Sans } from 'next/font/google'

// Configure font variations
const inter = Mulish({ 
  subsets: ['latin'],
  weight: ['300','400','500','600','700','800','900'],
  display: 'swap'
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${inter.className}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
